### ISSUE TITLE
500 error when activating plugin

### ISSUE THREAD

**Issue by jacestk** [SondagesPro/LS-sendMailAjax#3]
When cliking on "activate" in pligin menu, I got a 500 error:
> Erreur interne du serveur
> CClientScript and its behaviors do not have a method or closure named "hasPackage".

> Une erreur interne est apparue lorsque le serveur web traitait votre requete. Veuillez contacter the webmaster pour signaler ce problème.

> Merci. 

LimeSurvey Version 2.50.1+160823
PHP 5.4
Apache 2.4
CentOS Linux release 7.3.1611 (Core)

The problem seems to come from hasPackage() method for line 484

**Comment by Shnoulle** [comment]
For 2.50 : maybe you can test with https://gitlab.com/SondagesPro/mailing/sendMailAjax/blob/7f716efe72f4774a9c405ac20f260b374cf6b9e9/sendMailAjax.php . I make a realease 'legacy' for this.

Else : https://www.yiiframework.com/doc/api/1.1/CClientScript#hasPackage-detail the it's OK on last LimeSurvey version (2.73 too).

**Comment by Shnoulle** [comment]
LS updated to 1.1.18  since https://github.com/LimeSurvey/LimeSurvey/commit/b86cf0b6873eb56d89b3b55065c55ee982ea6ecf#diff-756457dc85f13450b3dfba2cbc1465e5

https://github.com/SondagesPro/LS-sendMailAjax/commit/71c2661c48e0efe6bc6da8e02d58b79610efb84c

and

https://github.com/SondagesPro/LS-sendMailAjax/commit/ea67bd1283a570af72619172f68e86f3b7e9dc07
